language: python
python:
  - "3.4"

install: pip install tox && sudo apt-get update && sudo apt-get install php-cli

script: tox && find . \( -name "*.php" -or -name "*.phtml" \) -print0 | xargs -0 -n 1 php -l
